In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
import h5py
import numpy as np

In [2]:
#Importing TCGA RNA expression data downloaded from  https://amp.pharm.mssm.edu/archs4/download.html
filename = "tcga_matrix.h5"

h5 = h5py.File(filename,'r')
for k in h5.keys():
    print(k)


meta = h5['meta']  
dat = h5['data']  
info = h5['info']  



#Showing which type of data it contains    
for s in meta.keys():
    print(s)
    print(meta[s].shape)
    print(meta[s].value)
    
for s in dat.keys():
    print(s)
    print(dat[s].shape)
    print(dat[s].value)    
    
for s in info.keys():
    print(s)
    print(info[s].shape)
    print(info[s].value)    

#h5.close()

meta
data
info
auc
(11284,)
[b'3116748351' b'5069849036' b'4882401623' ... b'5742234142' b'6773612787'
 b'7613399024']
bigwig_file
(11284,)
[b'3DFF72D2-F292-497E-ACE3-6FAA9C884205.bw'
 b'B1E54366-42B9-463C-8615-B34D52BD14DC.bw'
 b'473713F7-EB41-4F20-A37F-ACD209E3CB75.bw' ...
 b'76987B28-B56B-4A1F-B77C-1E08B8EFEF90.bw'
 b'33737781-8638-4FA2-AD4C-E888BB9343D8.bw'
 b'0BB05CA7-C6FF-42A1-919C-D801F471CBBD.bw']
cancertype
(11284,)
[b'Liver Hepatocellular Carcinoma' b'Prostate Adenocarcinoma'
 b'Rectum Adenocarcinoma' ... b'Brain Lower Grade Glioma'
 b'Acute Myeloid Leukemia' b'Thyroid Carcinoma']
gdc_annotations
(11284,)
[b'NULL' b'NULL' b'NULL' ... b'NULL'
 b'list(category = "Alternate sample pipeline", status = "Approved", entity_id = "fff35c80-88cd-4923-80c1-0273ba5bed0f", classification = "Notification", updated_datetime = "2016-05-01T15:00:21.638875-05:00", created_datetime = "2012-11-13T12:37:22-05:00", entity_submitter_id = "TCGA-AB-2881", notes = "Biospecimens from this case belong t

[[1454762  439935  316636 ...  302428   29863   44717]
 [  28886   23917     192 ... 1009426  156109  108371]
 [   4322    9719  154254 ... 1319876  348923  253112]
 ...
 [  10570   16608     220 ...  402715  307415   85944]
 [  28190   52035     157 ... 1888391  660036  369616]
 [  40426   40053      48 ...  793314  481256  313210]]
author
(1,)
[b'Alexander Lachmann']
contact
(1,)
[b'alexander.lachmann@mssm.edu']
countsource
(1,)
[b'recount2: https://jhubiostatistics.shinyapps.io/recount/']
creationdate
(1,)
[b'10/9/2017']
lab
(1,)
[b"Ma'ayan Lab, Icahn School of Medicine"]


In [3]:
#Importing pathway enrichment analysis for 50 Cancer Hallmark pathways http://software.broadinstitute.org/gsea/msigdb/collections.jsp#H
#In gmt format each gene set is a row and is described by a name, a description, and the genes in the gene set
import pandas as pd

H50 = pd.read_csv('h.all.v6.2.symbols.gmt', header = None, sep='\t')
H50.head()




0    \
0     HALLMARK_TNFA_SIGNALING_VIA_NFKB   
1                     HALLMARK_HYPOXIA   
2     HALLMARK_CHOLESTEROL_HOMEOSTASIS   
3             HALLMARK_MITOTIC_SPINDLE   
4  HALLMARK_WNT_BETA_CATENIN_SIGNALING   

                                                 1        2        3      4    \
0  http://www.broadinstitute.org/gsea/msigdb/card...     JUNB    CXCL2   ATF3   
1  http://www.broadinstitute.org/gsea/msigdb/card...     PGK1     PDK1   GBE1   
2  http://www.broadinstitute.org/gsea/msigdb/card...     FDPS  CYP51A1   IDI1   
3  http://www.broadinstitute.org/gsea/msigdb/card...  ARHGEF2   CLASP1  KIF11   
4  http://www.broadinstitute.org/gsea/msigdb/card...      MYC   CTNNB1   JAG2   

      5        6      7       8      9     ...      192     193       194  \
0  NFKBIA  TNFAIP3  PTGS2   CXCL1   IER3   ...     EIF1    BMP2     DUSP4   
1    PFKL    ALDOA   ENO2    PGM1  NDRG1   ...    HDLBP   ILVBL      NCAN   
2   FDFT1    DHCR7   SQLE  HMGCS1  NSDHL   ...      NaN     NaN       NaN   
3   KIF23     ALS2   ARF6   MYO9B   MYH9   ...    RHOT2  SORBS2  CDC42EP1   
4  NOTCH1     DLL1  AXIN2   PSEN2   FZD1   ...      NaN     NaN       NaN   

      195     196     197       198      199       200     201  
0  PDLIM5  ICOSLG   GFPT2      KLF2      TNC  SERPINB8    MXD1  
1    TGM2    ETS1   HOXB9  SELENBP1    FOSL2   SULT2B1   TGFB3  
2     NaN     NaN     NaN       NaN      NaN       NaN     NaN  
3     VCL   CLIP1  STK38L     YWHAE  RAPGEF5     CEP72  CSNK1D  
4     NaN     NaN     NaN       NaN      NaN       NaN     NaN  

[5 rows x 202 columns]

In [5]:
#Add H50 gen sets as a categorical variable 

In [8]:
#Different genes involved in 50 selected signaling pathways 
genePath_set = pd.unique(H50.loc[:,2:].values.ravel('K'))
genePath_set.size

4387

In [9]:
H50.shape

(50, 202)

In [9]:

# log2(TPM+0.001) expression values computed per gene
# Uncomment to regenerate
#expression = dat['expression'].value
#def f(x):
    # return log2(TPM+0.001)
    #return np.log2(x +0.001 ) 
#expression = np.vectorize(f)(expression)
#expression

In [10]:
#from scipy import stats
#stats.describe(expression)

In [11]:
#np.save('log2expression.npy', expression)


In [5]:
l = np.load('log2expression.npy')
l

array([[20.47235172, 18.74693086, 18.27246577, ..., 18.2062322 ,
        14.86607153, 15.44853581],
       [14.81808287, 14.54574888,  7.58497001, ..., 19.94510372,
        17.2521942 , 16.72561923],
       [12.07748369, 13.24659231, 17.23494838, ..., 20.33197097,
        18.41254918, 17.94941639],
       ...,
       [13.36768789, 14.01959082,  7.78136627, ..., 18.61939969,
        18.22982804, 16.39110932],
       [14.78289591, 15.66719475,  7.29462994, ..., 20.84872608,
        19.33218519, 18.49566769],
       [15.30299588, 15.28962272,  5.58499256, ..., 19.59753249,
        18.876445  , 18.25677075]])

In [7]:
#associate gene names with RNA expression
def f(x):
    return x.decode("utf-8")
genes = np.vectorize(f)(meta['genes'].value)
df = pd.DataFrame(l, columns = genes)
df.describe()

A1BG      A1BG-AS1          A1CF           A2M       A2M-AS1  \
count  11284.000000  11284.000000  11284.000000  11284.000000  11284.000000   
mean      14.511335     14.658286      7.818664     21.170343     16.323402   
std        2.262990      1.781519      7.636277      1.819773      1.530948   
min        4.906939      4.392386     -9.965784     10.540129      8.876520   
25%       13.115125     13.612897      6.247946     20.103902     15.396688   
50%       14.377075     14.614969      7.936644     21.240994     16.313299   
75%       15.611969     15.556147     11.956830     22.350001     17.271283   
max       25.744343     23.457815     21.781484     27.526837     22.749258   

              A2ML1         A2MP1       A3GALT2        A4GALT         A4GNT  \
count  11284.000000  11284.000000  11284.000000  11284.000000  11284.000000   
mean      11.515712     10.927732      3.512874     16.375104      4.546174   
std        5.025257      2.047451      7.174155      1.840625      7.976631   
min       -9.965784     -9.965784     -9.965784      6.988696     -9.965784   
25%        8.640249     10.006678      3.322072     15.161555      4.807406   
50%       10.918491     11.040290      6.584978     16.524121      7.584970   
75%       14.611140     12.092427      8.029291     17.722402      9.205794   
max       25.852982     18.892860     14.192447     21.365289     20.369699   

           ...             ZWILCH         ZWINT          ZXDA          ZXDB  \
count      ...       11284.000000  11284.000000  11284.000000  11284.000000   
mean       ...          16.317508     16.803166     14.481343     16.262297   
std        ...           1.238517      1.550544      1.295317      1.108982   
min        ...           9.238407      8.906894     -9.965784      7.584970   
25%        ...          15.450841     15.698264     13.734075     15.639362   
50%        ...          16.299789     16.862601     14.602264     16.340676   
75%        ...          17.199718     17.988194     15.369069     16.953637   
max        ...          20.524677     21.309852     17.978504     20.607729   

               ZXDC        ZYG11A        ZYG11B           ZYX         ZZEF1  \
count  11284.000000  11284.000000  11284.000000  11284.000000  11284.000000   
mean      17.164771     11.034740     17.568689     19.878162     18.062571   
std        0.948553      4.794702      1.120799      1.148660      1.065064   
min       11.969387     -9.965784     10.388018     14.118455     12.988152   
25%       16.617780      9.012625     16.962933     19.163031     17.430391   
50%       17.227212     11.866893     17.655066     19.896538     18.149090   
75%       17.761895     14.115450     18.333242     20.566523     18.753259   
max       20.899094     21.113483     22.043753     24.416677     22.150687   

               ZZZ3  
count  11284.000000  
mean      17.549486  
std        0.987241  
min       11.607331  
25%       16.973854  
50%       17.624513  
75%       18.193407  
max       21.651597  

[8 rows x 25150 columns]

In [6]:
#One hot 50 signaling pathways for each instance
#1. Select only genes involved in pathways
print(genePath_set)
genePath_I_geneRNA= set(df.columns).intersection(set(genePath_set))
print(len(genePath_I_geneRNA))
df_s = df[list(genePath_I_geneRNA)]
print("RNA exp gene matrix reduced to only genes in pathways")
print(df_s.shape)




NameError: name 'genePath_set' is not defined

In [4]:
#2. Add result of pathway enrichment analysis for 50 Cancer Hallmark pathways as categorical variables: 
#Array of 50 boolean
#If all genes involved on each signaling pathway from H50 are RNA log2 expressed > 0 then this pathway is assigned True in the sample
def f(row):
    a = []
    for index, p in H50.iterrows():
        #print(p)
        #exclude from pathway genes 'p' those that are not in genePath_I_geneRNA (Total 83)
        p_s = set(p[2:]).intersection(genePath_I_geneRNA)
        rna = row[list(p_s)]
        #print (rna)
        a.append(np.all(rna.values > 0))
    return np.array(a)
df_s['H50_onehot'] = df_s.apply(f, axis=1)
#Merge H50 onehot with the full RNA expression matrix
df['H50_onehot'] = df_s['H50_onehot'] 
df.to_pickle("RNAexp_H50onehot.pkl")




NameError: name 'df_s' is not defined

In [4]:
#Add the ground truth: tumor type for each instance
#Load processed data
df = pd.read_pickle('RNAexp_H50onehot.pkl')
df.loc[:,'cancertype']= pd.Series(meta['cancertype'].value)
df.head()

A1BG   A1BG-AS1       A1CF        A2M    A2M-AS1      A2ML1  \
0  20.472352  18.746931  18.272466  19.290201  15.257498  -9.965784   
1  14.818083  14.545749   7.584970  21.170981  17.082887  13.392988   
2  12.077484  13.246592  17.234948  20.949892  14.822969   6.700454   
3  24.457885  22.684448  19.907039  23.860669  19.778088   7.918869   
4  11.676398  12.256504   8.076821  19.457004  14.529736  17.318905   

       A2MP1   A3GALT2     A4GALT     A4GNT  \
0   9.299210  5.643885  13.595724 -9.965784   
1  10.586841  3.322072  17.862692 -9.965784   
2  10.472692  7.321937  16.977783  7.044405   
3  13.952559  1.000721  16.081317 -9.965784   
4   8.209458 -9.965784  17.581149 -9.965784   

                 ...                       ZXDA       ZXDB       ZXDC  \
0                ...                  11.805341  13.000000  15.517669   
1                ...                  13.460072  15.752668  16.611414   
2                ...                  15.637785  17.493347  16.861135   
3                ...                  12.749870  15.258603  16.945592   
4                ...                  13.757911  15.446534  17.096242   

      ZYG11A     ZYG11B        ZYX      ZZEF1       ZZZ3  \
0   9.278452  15.699383  18.206232  14.866072  15.448536   
1  12.744834  16.470659  19.945104  17.252194  16.725619   
2   8.839207  17.636320  20.331971  18.412549  17.949416   
3  12.561527  18.267911  16.341345  17.340346  17.422426   
4  12.186734  17.651276  20.299427  17.006589  17.689343   

                                          H50_onehot  \
0  [False, False, False, True, False, False, Fals...   
1  [True, False, True, True, True, True, False, T...   
2  [True, False, True, True, True, True, False, T...   
3  [False, False, True, True, True, True, False, ...   
4  [False, False, True, True, False, True, False,...   

                          cancertype  
0  b'Liver Hepatocellular Carcinoma'  
1         b'Prostate Adenocarcinoma'  
2           b'Rectum Adenocarcinoma'  
3  b'Liver Hepatocellular Carcinoma'  
4    b'Bladder Urothelial Carcinoma'  

[5 rows x 25152 columns]

In [5]:
H50_categories = pd.DataFrame(df.H50_onehot.tolist(), columns = H50.loc[:,0].values)
df_categories = df.join(H50_categories)
df_categories.H50_onehot
print(df_categories.shape)
df_categories.to_pickle("RNAexp_H50cat_tumorTypes.pkl")
df_categories = df_categories.drop(columns=['H50_onehot'])
df_categories.shape


(11284, 25202)


(11284, 25201)

In [7]:
#Use FastAI 
from fastai import *
from fastai.tabular import * 

procs = [FillMissing, Categorify, Normalize]
dep_var = 'cancertype'
cat_names = H50.loc[:,0].values #all other fields not in dep_var or cat_names are handled as continous variables
valid_idx = range(len(df_categories)-3000, len(df_categories))
df_categories['cancertype'] = pd.Categorical(df_categories.cancertype)
df_categories['cancertype'] = df_categories.cancertype.cat.codes
df_categories['cancertype'].describe()

count    11284.000000
mean        15.014002
std          9.301482
min          0.000000
25%          7.000000
50%         14.000000
75%         23.000000
max         32.000000
Name: cancertype, dtype: float64

In [8]:

data = TabularDataBunch.from_df('./', df_categories, dep_var=dep_var, valid_idx=valid_idx, procs=procs, cat_names=cat_names)

#print(data.train_ds.cont_names)  # `cont_names` defaults to: set(df)-set(cat_names)-{dep_var}

learn = tabular_learner(data, layers=[500,50], metrics=accuracy, ps=[.2,.1])
learn.fit(33, 1e-2)

Total time: 02:40
epoch  train_loss  valid_loss  accuracy
1      0.503842    0.241396    0.923333  (00:04)
2      0.227772    0.213783    0.927000  (00:04)
3      0.127209    0.185534    0.940333  (00:04)
4      0.090626    0.199434    0.939333  (00:04)
5      0.077104    0.212278    0.934000  (00:04)
6      0.049125    0.217233    0.950000  (00:04)
7      0.037340    0.340264    0.932000  (00:04)
8      0.046956    0.250232    0.947000  (00:04)
9      0.032279    0.284934    0.935000  (00:04)
10     0.028284    0.307077    0.931000  (00:04)
11     0.026738    0.246928    0.948000  (00:04)
12     0.025021    0.407419    0.933333  (00:04)
13     0.022676    0.260365    0.951000  (00:05)
14     0.018009    0.257445    0.951333  (00:04)
15     0.025444    0.249987    0.949000  (00:04)
16     0.013448    0.248825    0.956000  (00:04)
17     0.019259    0.323733    0.941333  (00:04)
18     0.009642    0.237344    0.950000  (00:04)
19     0.023478    0.252720    0.950000  (00:04)
20     0.01